Add gnome-keyring as deb dependency
shiftkey/desktop pull request #186
Opened 2019-10-18 23:30 UTC by jeffdgr8

Closes https://github.com/shiftkey/desktop/issues/180

## Description

Add gnome-keyring as deb dependency

### Screenshots

N/A

## Release notes

Notes: no-notes

2019-11-01 14:32 UTC, RaspberryPiFan commented
https://github.com/jeffdgr8/desktop/pull/1

2019-11-03 11:45 UTC, ghost requested changes
You forgot to add this to deb, you added it only to rpm

2019-11-05 20:17 UTC, jeffdgr8 commented
@RaspberryPiFan done

2019-11-24 19:24 UTC, RaspberryPiFan commented
@shiftkey Have you seen this PR?

2020-02-04 21:49 UTC, shiftkey commented
Thanks @jeffdgr8 for the contribution and @RaspberryPiFan for the review!

2020-02-04 21:49 UTC, shiftkey approved these changes

2020-02-04 21:49 UTC, merged